### ISSUE TITLE
the dataset for training normal network

### ISSUE THREAD

**Issue by Jiatttliu** [shad0wta9/meshavatar#1]
I have obtained the permission for the dataset of thuman2.0, but I have encountered some problems when using ICON to process the dataset. Could you please provide the dataset that you have processed?

**Comment by shad0wta9** [comment]
Sorry, we didn’t test our method on THuman2.0 dataset, so we haven’t processed normals for it.
If you have further question, feel free to comment here!

**Comment by Jiatttliu** [comment]
I'm sorry I didn't state my question clearly. I have finished processing the THuman2.0 dataset. 

In section 3.5 of the paper, you say that you used THuman2.0 to train a normal prediction network. 
`For this purpose, we utilize 3D human scans collected from [99] to train a normal estimation network.` 

According to my idea, this network can give a corresponding normal map based on the input image after the training is completed, even if the image is not in the training dataset. Am I right?

**Comment by shad0wta9** [comment]
Yes, the normal prediction network is trained using scans from THuman2.0.
By the way, we have ground truth scanned meshes in THuman2.0, so I think there is no need to process using ICON.
