### ISSUE TITLE
About the backbone network? (unet or styleunet)

### ISSUE THREAD

**Issue by JanaldoChen** [shad0wta9/meshavatar#10]
Hello, author. While reading your paper, I noticed that in your diagram you used StyleUNet (which is used in AnimatableGaussian), but in the open-source code, it is a standard UNet. Are these two consistent with each other? I am currently obtaining very poor results on my own dataset. Could this be due to the backbone? (As discussed in the AnimatableGaussian paper, StyleUNet shows significant improvement over UNet and MLP.)"

**Comment by shad0wta9** [comment]
We have tested this after the paper is submitted, and found standard unet is better.
What is your "very poor results"? The network backbone has little impact to the performance.

**Comment by JanaldoChen** [comment]
Sorry for the delay, here is an example on ActorHQ [the actor02 sequence 02]. Is the result normal?

https://github.com/user-attachments/assets/a23eba60-2779-4921-94d7-356639f7a4f2

**Comment by shad0wta9** [comment]
I think the result meets the expectation.
Our method has limitation to reconstruct loose clothes. The performance will be better if using Sequence 1, as shown in the paper.

**Comment by JanaldoChen** [comment]
Thanks for your reply! I will close the issue.

**Comment by trThanhnguyen** [comment]
Hi @JanaldoChen , I would like to reproduce the results on ActorsHQ, too. May I ask for your implementation of the dataloader for ActorsHQ? It's missing from the code release. Thanks in advance.
