### ISSUE TITLE
Question about the code release schedule

### ISSUE THREAD

**Issue by Haodong-Yan** [shad0wta9/meshavatar#2]
Hi, I'm very interested in your great work. I want to know the rough date for code realse.

**Comment by shad0wta9** [comment]
Maybe in 1 or 2 weeks.

**Comment by Haodong-Yan** [comment]
I‘m a little confused about how to extracted delta v from the offset map via eq 5. Could you provide this part of code in advance? And is the delta v in canonical space or posed space? Thank you very much.

**Comment by shad0wta9** [comment]
1. delta v is extracted using bilinear interpolation from offset map.
2. delta v is defiend in posed space.

**Comment by Haodong-Yan** [comment]
thanks!
