### ISSUE TITLE
Sparse-view reconstruction performance and performance vs AnimatableGaussians

### ISSUE THREAD

**Issue by gwang-kim** [shad0wta9/meshavatar#5]
Hi,

Thank you for the great work!
I'm curious about the performance of sparse-view reconstruction (e.g. 2-view, 4-view). How good it is? Is there the mimimum number of views for the stable results?

Also, comparing with AnimatableGaussians, are there any pros and cons?

Thank you in advance!

**Comment by shad0wta9** [comment]
We didn't test our method on sparse-view scenarios. But when we want accurate geometry or support relighting, I think dense views are necessary.

You can check Appendix A in the paper to see some discussion on the comparisons with AnimatableGaussians.

**Comment by gwang-kim** [comment]
I see. Thank you for your insight!
