### ISSUE TITLE
Geometry crashed error

### ISSUE THREAD

**Issue by gwang-kim** [shad0wta9/meshavatar#6]
Hi,

Thank you again for your great work.
I ran into this issue with the following test results.
I think I have a wrong explicit skinned mesh?

`AssertionError: The geometry crashed (no triangles)! Please restart the program!`
![img_dmtet_pass1_000000](https://github.com/user-attachments/assets/5565b534-bd66-4990-9f38-8070606ad246)

**Comment by shad0wta9** [comment]
`calibration_full.json` should be modified when you resize the images.

**Comment by gwang-kim** [comment]
> `calibration_full.json` should be modified when you resize the images.


Thank you for the answer, @shad0wta9. Would you let me know how to resize it?

**Comment by shad0wta9** [comment]
You need to modify the intrinsic matrices in `calibration_full.json`
More specifically, if you resize the images into `1024x750` (scale x0.5), the intrinsic matrices should:
```
K[:2] *= 0.5
```

**Comment by gwang-kim** [comment]
Great, thank you!
